//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Darkhast.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SearchDarkhastNameSearchType {
            get {
                return ((int)(this["SearchDarkhastNameSearchType"]));
            }
            set {
                this["SearchDarkhastNameSearchType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SearchShomareFaniSearchType {
            get {
                return ((int)(this["SearchShomareFaniSearchType"]));
            }
            set {
                this["SearchShomareFaniSearchType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchDarkhastNameSearchRealTime {
            get {
                return ((bool)(this["SearchDarkhastNameSearchRealTime"]));
            }
            set {
                this["SearchDarkhastNameSearchRealTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchShomareFaniSearchRealTime {
            get {
                return ((bool)(this["SearchShomareFaniSearchRealTime"]));
            }
            set {
                this["SearchShomareFaniSearchRealTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ApplyInTrashStyle {
            get {
                return ((bool)(this["ApplyInTrashStyle"]));
            }
            set {
                this["ApplyInTrashStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ApplyTaeedShodeStyle {
            get {
                return ((bool)(this["ApplyTaeedShodeStyle"]));
            }
            set {
                this["ApplyTaeedShodeStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ApplyTaeedNashodeStyle {
            get {
                return ((bool)(this["ApplyTaeedNashodeStyle"]));
            }
            set {
                this["ApplyTaeedNashodeStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ApplyDarHaleBarresiStyle {
            get {
                return ((bool)(this["ApplyDarHaleBarresiStyle"]));
            }
            set {
                this["ApplyDarHaleBarresiStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SearchTozihatSearchType {
            get {
                return ((int)(this["SearchTozihatSearchType"]));
            }
            set {
                this["SearchTozihatSearchType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SearchTozihatSearchRealTime {
            get {
                return ((bool)(this["SearchTozihatSearchRealTime"]));
            }
            set {
                this["SearchTozihatSearchRealTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimerLoadGridViewDarkhasthaIsActive {
            get {
                return ((bool)(this["TimerLoadGridViewDarkhasthaIsActive"]));
            }
            set {
                this["TimerLoadGridViewDarkhasthaIsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int TimerLoadGridViewDarkhasthaPeriod {
            get {
                return ((int)(this["TimerLoadGridViewDarkhasthaPeriod"]));
            }
            set {
                this["TimerLoadGridViewDarkhasthaPeriod"] = value;
            }
        }
    }
}
